# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('new', 'new'), ('processing', 'processing'), ('done', 'done'), ('removed', 'removed')], default='new', max_length=10),
        ),
    ]
